apps/loginregistration/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'my_index'),
    url(r'success$', views.success, name = 'my_success' ),
    url(r'register$', views.register, name = 'my_register'),
    url(r'login$', views.login, name = 'my_login'),
]

apps/wish_list/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'my_index'),
    url(r'^logout$', views.logout, name = 'my_logout'),
    url(r'^take', views.take, name = 'my_take'),
    url(r'^remove', views.remove, name = 'my_remove'),
    url(r'^add$', views.add, name = 'my_add'),
    url(r'^delete$', views.delete, name = 'my_delete'),
    url(r'^create$', views.create, name = 'my_create'),
    url(r'^wish_items/(?P<id>\d+)', views.items, name = 'my_items'),

]

belt_exam/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.loginregistration.urls', namespace = 'users')),
    url(r'^wishlist/', include('apps.wish_list.urls', namespace = 'wish')),
]

apps/loginregistration/models.py
from __future__ import unicode_literals

from django.db import models

class UserManager(models.Manager):
	def login(self, postData):
		print "Login Successful"
		pass
	def register(self, postData):
		print "Registration Succesful"
		pass

class User(models.Model):
	first_name = models.CharField(max_length=255)
	last_name = models.CharField(max_length=255)
	email = models.CharField(max_length=255)
	password = models.CharField(max_length=255)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)
	objects = UserManager()

apps/wish_list/models.py
from __future__ import unicode_literals
from django.db import models
from ..loginregistration.models import User
# from django.db import User

class Item(models.Model):
    name = models.CharField(max_length=255)
    user = models.ManyToManyField(User, related_name="items")
    added_by = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/loginregistration/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User
import bcrypt
import re

EMAIL_REGEX = r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$'
NAME_REGEX = r'^[0-9.+_-]'


def index(request):
    # User.objects.all().delete()
    request.session['email'] = ""
    request.session['username'] = ""
    # request.session['this_user'] = []
    return render(request,'loginregistration/index.html')
def success(request):
    context = {
        "users": User.objects.get(email = request.session['email'])
    }
    return render(request,'loginregistration/success.html',context)
def register(request):
    request.session['username'] = ""
    first_name = request.GET['first_name']
    last_name = request.GET['last_name']
    email = request.GET['email']
    password =  request.GET['password']
    pwconfirm = request.GET['pwconfirm']
    errors = 0
    try:
        User.objects.get(email = email)
        messages.add_message(request, messages.INFO, "email already in use!")
        return redirect('/')
    except:
        if len(first_name) < 3:
            errors += 1
            messages.add_message(request, messages.INFO, "first name too short!")
        if re.match(NAME_REGEX, first_name):
            errors += 1
            messages.add_message(request, messages.INFO, "first name must only contain letters!")
        if re.match(NAME_REGEX, last_name):
            errors += 1
            messages.add_message(request, messages.INFO, "last name must only contain letters!")
        if len(last_name) < 3:
            errors += 1
            messages.add_message(request, messages.INFO, "last name too short!")
        if not re.match(EMAIL_REGEX,email):
            errors += 1
            messages.add_message(request, messages.INFO, "invalid email!")
        if len(password) < 8:
            errors += 1
            messages.add_message(request, messages.INFO, "password too short!")
        if not password == pwconfirm:
            errors += 1
            messages.add_message(request, messages.INFO, "passwords must match!")
        if errors == 0:
            hashed = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
            User.objects.create(first_name=first_name,last_name=last_name,email=email,password=hashed)
            print User.objects.all()
            request.session['username'] = first_name
            request.session['email'] = email
            return redirect('wish:my_index')
        else:
            return redirect('/')

def login(request):
    email = request.GET['email']
    password =  request.GET['password']
    try:
        user = User.objects.get(email = email)
    except UnboundLocalError:
        messages.add_message(request, messages.INFO, "email does not match any account!")
        return redirect('/')
    except:
        messages.add_message(request, messages.INFO, "email does not match any account!")
        return redirect('/')
    if bcrypt.hashpw(password.encode(), user.password.encode()) == user.password:
        request.session['email'] = email
        request.session['username'] = user.first_name
        # request.session['this_user'] = User.objects.get(email = email)
        return redirect('wish:my_index')
    else:
        messages.add_message(request, messages.INFO, "incorrect password!")
    return redirect('/')

apps/wish_list/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .models import Item
from ..loginregistration.models import User


def index(request):
    context = {
	   "All_Items": Item.objects.all(),
	   "All_Users": User.objects.all(),
	   "This_Items_Me": Item.objects.filter(user__email=request.session['email'], added_by=request.session['username']),
	   "This_Items_Them": Item.objects.filter(user__email=request.session['email']).exclude(added_by=request.session['username']),
       "Other_Items": Item.objects.exclude(user__email=request.session['email']),
    }
    return render(request, 'wish_list/index.html', context)

def logout(request):
    return redirect('users:my_index')

def add(request):
    # Item.objects.all().delete()
    return render(request, 'wish_list/create.html')
def items(request, id):
    request.session['id'] = id
    context = {
        "This_Item": Item.objects.get(id = id),
        "These_Users": User.objects.filter(items__id = id)
    }
    return render(request, 'wish_list/items.html', context)

def create(request):
    user_email = request.session['email']
    this_user = User.objects.get(email = user_email)
    item_name = request.GET['item']
    errors = 0
    try:
        item = Item.objects.get(name = item_name)
        this_user.items.add(item)
        this_user.save()
        print "double item"
        # Item.objects.get(name = item_name).add(user = this_user)
        messages.add_message(request, messages.INFO, "Item already listed")
        return redirect('wish:my_add')
    except:
        if len(item_name) < 3:
            errors += 1
            messages.add_message(request, messages.INFO, "item name must be longer than 3 characters!")
            return redirect('wish:my_add')
        if errors == 0:
            item = Item.objects.create(name = item_name, added_by =request.session['username'])
            item.save
            this_user.items.add(item)
            this_user.save()
        return redirect('wish:my_index')
    return redirect('wish:my_index')

def take(request):
    this_user = User.objects.get(email = request.session['email'])
    this_item = Item.objects.get(id = request.GET['id'])
    this_user.items.add(this_item)
    this_item.save()
    this_user.save()
    return redirect('wish:my_index')

def remove(request):
    this_user = User.objects.get(email = request.session['email'])
    this_item = Item.objects.get(id = request.GET['id'])
    this_user.items.remove(this_item)
    this_item.save()
    this_user.save()
    return redirect('wish:my_index')

def delete(request):
    this_item = Item.objects.get(id = request.GET['id'])
    this_item.delete()
    return redirect('wish:my_index')




# Create your views here.

apps/loginregistration/templates/loginregistration/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    <form id="registrationform" action='/register' methods="get">
      <h1>Registration</h1>
      <p>First Name: <input type="text" name='first_name'></p>
      <p>Last Name: <input type="text" name='last_name'></p>
      <p>Email: <input type="text" name='email'></p>
      <p>Password: <input type="password" name='password'></p>
      <p>Confirm PW: <input type="password" name='pwconfirm'></p>
      <button type="submit" name="register">Register</button>
    </form>
    <form id="loginform" action='/login' methods="post">
      <h1>Login</h1>
      <p>Email: <input type="text" name="email"></p>
      <p>Password: <input type="password" name="password"></p>
      <button type="submit" name="login">Login</button>
    </form>
  </body>
</html>

apps/loginregistration/templates/loginregistration/success.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'first_app/css/style.css' %}">
    <title>Success</title>
  </head>
  <body>
    <h1>Success! Welcome, {{request.session.username}}!</h1>
    <p><font color="green">Successfully registered (or logged in)!</font></p>
  </body>
</html>

apps/wish_list/templates/wish_list/create.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> Create Item</title>
  </head>
  <body>
    <div id = "header">
      <a href="{% url 'wish:my_index' %}">Home</a>
      <a href="{% url 'wish:my_logout' %}">Logout</a>
    </div>
    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}
    <form action = "create" method="get">
      {% csrf_token %}
      Item/Product <input type='text' name='item'>
      <button type="submit" name="add">Add</button>
    </form>
  </body>
</html>

apps/wish_list/templates/wish_list/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> My Wish List</title>
  </head>
  <body>
    <div id = "header">
      <h1>Hello, {{request.session.username}}!</h1>
      <a href="{% url 'wish:my_logout' %}">Logout</a>
      <a href="{% url 'wish:my_add' %}">Add Item</a>
    </div>
    <h2>Your Wish List</h2>
    <table>
      <tr>
        <th>Item</th>
        <th>Added by</th>
        <th>Date Added</th>
        <th>Action</th>
      </tr>
      {% for item in This_Items_Them %}
        <tr>
          <td><a href = "{% url 'wish:my_items' id=item.id %}">{{item.name}}</a></td>
          <td>{{item.added_by}}</td>
          <td>{{item.created_at}}</td>
          <td>
            <form action="remove" method="get">
              <input type="hidden" name="id" value={{item.id}}>
              <button type="submit" value="add">Remove From My Wishlist</button>
            </form>
          </td>
        </tr>
      {% endfor %}
      {% for item in This_Items_Me %}
        <tr>
          <td><a href = "{% url 'wish:my_items' id=item.id %}">{{item.name}}</a></td>
          <td>{{item.added_by}}</td>
          <td>{{item.created_at}}</td>
          <td>
            <form action="delete" method="get">
              <input type="hidden" name="id" value={{item.id}}>
              <button type="submit" value="add">Delete Item</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </table>

    <h2>Other Users' Wish List</h2>
    <table>
      <tr>
        <th>Item</th>
        <th>Added by</th>
        <th>Date Added</th>
        <th>Action</th>
      </tr>
      {% for item in Other_Items %}
        <tr>
          <td><a href = "{% url 'wish:my_items' id=item.id %}">{{item.name}}</a></td>
          <td>{{item.added_by}}</td>
          <td>{{item.created_at}}</td>
          <!-- <td><a href="{% url 'wish:my_take' %}"> Add to my wishlist</a></td> -->
          <td>
            <form action="take" method="get">
              <input type="hidden" name="id" value={{item.id}}>
              <button type="submit" value="add">Add to My Wishlist</button>
            </form>
          </td>
        </tr>
      {% endfor %}
      </ul>
    </table>
  </body>
</html>

apps/wish_list/templates/wish_list/items.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{{This_Item.name}}</title>
  </head>
  <div id = "header">
    <a href="{% url 'wish:my_index' %}">Home</a>
    <a href="{% url 'wish:my_logout' %}">Logout</a>
  </div>
  <body>
    <h1>{{This_Item.name}}</h1>
    <p> Users who added this product/item under their wish list:</p>
    {% for user in These_Users %}
      <p>{{user.first_name}}</p>
    {% endfor%}

  </body>
</html>

wish_list/templates/wish_list/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title> My Wish List</title>
  </head>
  <body>
    <div id = "header">
      <h1>Hello, {{request.session.username}}!</h1>
      <a href="{% url 'books:my_add' %}">Add Book and Review</a>
      <a href="{% url 'books:my_logout' %}">Logout</a>
    </div>
  </body>
</html>